name: Deploy prod app
on: 
  push:
    branches:
      - production-branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: ssh
      - name: SSH Deploy
        env:
            username: ${{ secrets.USER }} # Your server's username
            key: ${{ secrets.SSH_PRIVATE_KEY }} # Your server's SSH private key
            script: |
              cd /root/Fined # Specify the path to your app directory on the server
              git switch production-branch
              git pull
              npm install
              npm run build
              pm2 restart fined-site # Replace with your PM2 service name
